[project]
name = "mujoco-mjx-pixi-example"
version = "0.1.0"
description = "Example of using MuJoCo MJX with CUDA acceleration and pixi"
authors = ["Silvio Traversaro <silvio.traversaro@iit.it>"]
channels = ["conda-forge", "nvidia"]
platforms = ["linux-64"]

[system-requirements]
unix = true
cuda = "11.8"

[tasks]
tutorial_notebook = "jupyter notebook tutorial.ipynb"

[dependencies]
brax       = "0.9.3.*"
mujoco     = "3.0.0.*"
mujoco-mjx = "3.0.0.*"
notebook   = "*"
mediapy    = "*"
cuda-nvcc  = "11.8.*"
