[project]
name = "mujoco-mjx-pixi-example"
version = "0.2.0"
description = "Example of using MuJoCo MJX with CUDA acceleration and pixi"
authors = ["Silvio Traversaro <silvio.traversaro@iit.it>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
cuda = "12"

[tasks]
notebook_tutorial = "jupyter notebook tutorial.ipynb"

[dependencies]
brax       = "*"
mujoco     = "3.1.3"
mujoco-mjx = "*"
notebook   = "*"
mediapy    = "*"
cuda-version = "12.*"
cuda-nvcc  = "*"
cuda-cupti = "*"
pip        = "*"
